% FUNCTION predValues = predCodeA_grp001( dataMatrix, testDataInd, kStep )
%
% This is an example examination function. Please see the function examCode
% for details. The input dataMatrix contains both the input(s) and output
% (to be predicted) signals, stored as separate columns in the matrix,
% preferably in the order provided in the project.
% 
% Note that all the data should be in the orginal domain; if you wish to do
% any transformations on any column, this should be done inside the
% function - and then the prediction should be return to the original 
% domain in the return variable predValues. 
% 
% The testDataInd indicated the test data to be evaluated. The prediction
% should be formed from the start of the provided data set, and the
% relevant period then being extracted, as shown below.
%

% Reference: 
%   "An Introduction to Time Series Modeling", 4th ed, by Andreas Jakobsson
%   Studentlitteratur, 2021
%
function predValues = predCodeA_grp001( dataMatrix, testDataInd, kStep )

outputData = dataMatrix(:,1);           % Extract the corresponding signals from the data matrix.
%inputData1  = dataMatrix(:,2);
%inputData2  = dataMatrix(:,3);


% Details of the used ARMA model. These are computed in the modeling part
% found in code28. Note that no modeling should be done in this function;
% there should thus not be any call to pem (or similar) in the function. 
Am = [ ...
    1.0000   -0.4884   -0.3333         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0   -1.0000    0.4884    0.3333         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0   -1.0000    0.4884    ...
    0.3333         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0    1.0000   -0.4884   -0.3333 ];
Cm = [ ...
    1.0000         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0   -0.6637         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0   -0.8416         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0         0         0         0         0         0         0         0         0    ...
         0         0    0.5854 ];

% Form the used preprocessing.
outputData = sqrt( outputData );

% Compute the predictions polynomials and form the prediction using ALL the
% data in order to avoid initialization problems.
[~, G] = polydivision( Cm, Am, kStep );
predValues = filter( G, Cm, outputData );

% Transform back to the measured domain; these are our predictions. 
predValues = predValues.^2;

% Extract the relevant part to return.
predValues = predValues(testDataInd);   
